
import { Box } from '@mui/material'
import Add from 'features/Add'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useAuth } from 'services/auth'

const Home: NextPage = () => {

  const { user } = useAuth()

  return (
    <div>
      <Head>
        <title>miniBot</title>
        <meta name="description" content="Generated by love" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user?.status === "USER" ? (
        <Box sx={{display: "flex" , alignItems:"center" , justifyContent: "center" , height:"100vh"}}>Non hai i permessi </Box>
      ) : (<Add />)}
    </div>
  )
}

export default Home
