
import Add from 'features/Add'
import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => (
  <div>
    <Head>
      <title>miniBot</title>
      <meta name="description" content="Generated by love" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Add />
  </div>
)

export default Home
