
import Settings from 'features/Settings'
import type { NextPage } from 'next'
import Head from 'next/head'


const User: NextPage = () => {

  return (
    <div>
      <Head>
        <title>miniBot | User</title>
        <meta name="description" content="Generated by love" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Settings />
    </div>
  )
}

export default User
