import { SpeedDial, SpeedDialAction, SpeedDialIcon } from '@mui/material'
import Settings from 'features/Settings'
import type { NextPage } from 'next'
import Head from 'next/head'
import AddIcon from '@mui/icons-material/Add';
import SearchIcon from '@mui/icons-material/Search';
import AccountCircleIcon from '@mui/icons-material/AccountCircle';
import { useRouter } from 'next/router';


const User: NextPage = () => {

  const router = useRouter()
  
  return (
    <div>
      <Head>
        <title>miniBot | User</title>
        <meta name="description" content="Generated by love" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SpeedDial
        ariaLabel="SpeedDial basic example"
        sx={{ position: 'fixed', bottom: 16, right: 16 }}
        icon={<SpeedDialIcon />}
      >
          <SpeedDialAction
            key={"add"}
            icon={<AddIcon/>}
            tooltipTitle={"Nuovo elemento"}
            onClick={()=> router.push("/")}
          />
           <SpeedDialAction
            key={"search"}
            icon={<SearchIcon/>}
            tooltipTitle={"Cerca elemento"}
          />
           <SpeedDialAction
            key={"user"}
            icon={<AccountCircleIcon/>}
            tooltipTitle={"Gestione utenti"}
            
          />
      </SpeedDial>
      <Settings />
    </div>
  )
}

export default User
